filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/nginx/access.log
  fields:
    log_source: "nginx"

output.logstash:
  hosts: ["logstash:5044"]
  index: "filebeat"  # Добавляем метаданные для индекса
